import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/auth-context";
import { CartProvider } from "@/context/cart-context";
import { ProviderProvider } from "@/context/provider-context";
import { FavoritesProvider } from "@/context/favorites-context";
import { NotificationsProvider } from "@/context/notifications-context";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-sans`}
      >
        <AuthProvider>
          <CartProvider>
            <ProviderProvider>
              <FavoritesProvider>
                <NotificationsProvider>
                  {children}
                  <Toaster richColors position="top-right" />
                </NotificationsProvider>
              </FavoritesProvider>
            </ProviderProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
